// Code generated by internal/generate/api/main.go; DO NOT EDIT.

package gateway

import (
	"context"
	"fmt"
	"github.com/browningluke/opnsense-go/pkg/api"
)

// Data structs

type GatewayRequest struct {
	Disabled                  string `json:"disabled"`
	Name                      string `json:"name"`
	Interface                 string `json:"interface"`
	IPProtocol                string `json:"ipprotocol"`
	Priority                  string `json:"priority"`
	Gateway                   string `json:"gateway"`
	DefaultGW                 string `json:"defaultgw"`
	FarGW                     string `json:"fargw"`
	MonitorDisable            string `json:"monitor_disable"`
	MonitorNoRoute            string `json:"monitor_noroute"`
	MonitorKillStates         string `json:"monitor_killstates"`
	MonitorKillStatesPriority string `json:"monitor_killstates_priority"`
	Monitor                   string `json:"monitor"`
	ForceDown                 string `json:"force_down"`
	Weight                    string `json:"weight"`
	LatencyLow                string `json:"latencylow"`
	LatencyHigh               string `json:"latencyhigh"`
	LossLow                   string `json:"losslow"`
	LossHigh                  string `json:"losshigh"`
	Interval                  string `json:"interval"`
	TimePeriod                string `json:"time_period"`
	LossInterval              string `json:"loss_interval"`
	DataLength                string `json:"data_length"`
	Description               string `json:"descr"`
}

type GetGateway struct {
	Disabled                  string           `json:"disabled"`
	Name                      string           `json:"name"`
	Description               string           `json:"descr"`
	Interface                 api.FieldOptions `json:"interface"`
	IPProtocol                api.FieldOptions `json:"ipprotocol"`
	Gateway                   string           `json:"gateway"`
	DefaultGW                 string           `json:"defaultgw"`
	FarGW                     string           `json:"fargw"`
	MonitorDisable            string           `json:"monitor_disable"`
	MonitorNoRoute            string           `json:"monitor_noroute"`
	MonitorKillStates         string           `json:"monitor_killstates"`
	MonitorKillStatesPriority string           `json:"monitor_killstates_priority"`
	Monitor                   string           `json:"monitor"`
	ForceDown                 string           `json:"force_down"`
	Priority                  string           `json:"priority"`
	Weight                    string           `json:"weight"`
	LatencyLow                string           `json:"latencylow"`
	LatencyHigh               string           `json:"latencyhigh"`
	LossLow                   string           `json:"losslow"`
	LossHigh                  string           `json:"losshigh"`
	Interval                  string           `json:"interval"`
	TimePeriod                string           `json:"time_period"`
	LossInterval              string           `json:"loss_interval"`
	DataLength                string           `json:"data_length"`
}

type GetGatewayResponse struct {
	Gateway GetGateway `json:"gateway_item"`
}

type Item struct {
	Interface                 string       `json:"interface"`
	Weight                    api.IntLike  `json:"weight"`
	IPProtocol                string       `json:"ipprotocol"`
	Name                      string       `json:"name"`
	Description               string       `json:"descr"`
	MonitorDisable            api.BoolLike `json:"monitor_disable"`
	GatewayInterface          bool         `json:"gateway_interface"`
	Iface                     string       `json:"if"`
	Dynamic                   bool         `json:"dynamic"`
	Virtual                   bool         `json:"virtual"`
	Priority                  api.IntLike  `json:"priority"`
	Attribute                 api.IntLike  `json:"attribute"`
	Gateway                   string       `json:"gateway"`
	UUID                      string       `json:"uuid"`
	Disabled                  bool         `json:"disabled"`
	Upstream                  bool         `json:"upstream"`
	DefaultGW                 bool         `json:"defaultgw"`
	InterfaceDescr            string       `json:"interface_descr"`
	Status                    string       `json:"status"`
	Delay                     string       `json:"delay"`
	StdDev                    string       `json:"stddev"`
	Loss                      string       `json:"loss"`
	LabelClass                string       `json:"label_class"`
	FarGW                     string       `json:"fargw"`
	MonitorNoRoute            string       `json:"monitor_noroute"`
	MonitorKillStates         string       `json:"monitor_killstates"`
	MonitorKillStatesPriority string       `json:"monitor_killstates_priority"`
	Monitor                   string       `json:"monitor"`
	ForceDown                 string       `json:"force_down"`
	LatencyLow                api.IntLike  `json:"latencylow"`
	CurrentLatencyLow         api.IntLike  `json:"current_latencylow"`
	LatencyHigh               api.IntLike  `json:"latencyhigh"`
	CurrentLatencyHigh        api.IntLike  `json:"current_latencyhigh"`
	LossLow                   api.IntLike  `json:"losslow"`
	CurrentLossLow            api.IntLike  `json:"current_losslow"`
	LossHigh                  api.IntLike  `json:"losshigh"`
	CurrentLossHigh           api.IntLike  `json:"current_losshigh"`
	Interval                  api.IntLike  `json:"interval"`
	CurrentInterval           api.IntLike  `json:"current_interval"`
	TimePeriod                api.IntLike  `json:"time_period"`
	CurrentTimePeriod         api.IntLike  `json:"current_time_period"`
	LossInterval              api.IntLike  `json:"loss_interval"`
	CurrentLossInterval       api.IntLike  `json:"current_loss_interval"`
	DataLength                api.IntLike  `json:"data_length"`
	CurrentDataLength         api.IntLike  `json:"current_data_length"`
}

type SearchResponse struct {
	Total    int    `json:"total"`
	RowCount int    `json:"rowCount"`
	Current  int    `json:"current"`
	Rows     []Item `json:"rows"`
}

// SettingsAddGateway executes the AddGateway RPC call of the Settings controller
func (c *Controller) SettingsAddGateway(ctx context.Context, gateway_item GatewayRequest) (*api.ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["gateway_item"] = gateway_item

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/add_gateway",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("AddGateway call failed: %w", err)
	}
	return result, nil
}

// SettingsSetGateway executes the SetGateway RPC call of the Settings controller
func (c *Controller) SettingsSetGateway(ctx context.Context, gateway_item GatewayRequest, uuid string) (*api.ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	bodyParams["gateway_item"] = gateway_item

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/set_gateway",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("SetGateway call failed: %w", err)
	}
	return result, nil
}

// SettingsSearchGateways executes the SearchGateways RPC call of the Settings controller
func (c *Controller) SettingsSearchGateways(ctx context.Context) (*SearchResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/search_gateway",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &SearchResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("SearchGateways call failed: %w", err)
	}
	return result, nil
}

// SettingsGetGateway executes the GetGateway RPC call of the Settings controller
func (c *Controller) SettingsGetGateway(ctx context.Context, uuid string) (*GetGatewayResponse, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/get_gateway",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &GetGatewayResponse{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("GetGateway call failed: %w", err)
	}
	return result, nil
}

// SettingsDeleteGateway executes the DeleteGateway RPC call of the Settings controller
func (c *Controller) SettingsDeleteGateway(ctx context.Context, uuid string) (*api.ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callParams = append(callParams, uuid)

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/del_gateway",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("DeleteGateway call failed: %w", err)
	}
	return result, nil
}

// SettingsApplyGateways executes the ApplyGateways RPC call of the Settings controller
func (c *Controller) SettingsApplyGateways(ctx context.Context) (*api.ActionResult, error) {

	callParams := []string{}
	bodyParams := make(map[string]interface{})

	callOpts := api.RPCOpts{
		BaseEndpoint:   "/routing/settings/reconfigure",
		Method:         "POST",
		PathParameters: callParams,
		BodyParameters: bodyParams,
	}

	resultData := &api.ActionResult{}
	result, err := api.Call(c.Client(), ctx, callOpts, resultData)
	if err != nil {
		return nil, fmt.Errorf("ApplyGateways call failed: %w", err)
	}
	return result, nil
}
